export default function TermsPage() {
    return (
        <main className="min-h-screen bg-charcoal-950 text-charcoal-100 px-6 py-12 font-sans">
            <div className="max-w-3xl mx-auto space-y-8">
                <h1 className="text-4xl font-display font-bold text-flame-500">Terms of Service</h1>
                <p className="text-charcoal-400">Last Updated: December 2025</p>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold text-charcoal-200">1. Acceptance of Terms</h2>
                    <p className="text-charcoal-300 leading-relaxed">
                        By connecting your wallet and using Wallet Roast (&quot;the Service&quot;), you agree to be bound by these Terms. If you do not agree, do not use the Service.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold text-charcoal-200">2. Experimental Software</h2>
                    <p className="text-charcoal-300 leading-relaxed">
                        Wallet Roast is experimental software running on the Base blockchain. It interacts with smart contracts that may contain bugs or vulnerabilities. You acknowledge that you are using the Service at your own risk.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold text-charcoal-200">3. No Financial Advice</h2>
                    <p className="text-charcoal-300 leading-relaxed">
                        The content generated by Wallet Roast is for entertainment purposes only. It is not financial, investment, or legal advice. Do not make financial decisions based on the &quot;roasts&quot; or scores provided.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold text-charcoal-200">4. Game Mechanics & Funds</h2>
                    <p className="text-charcoal-300 leading-relaxed">
                        The Service includes game mechanics involving a &quot;Pot&quot; and &quot;Points.&quot; You acknowledge that:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 text-charcoal-300">
                        <li>Blockchain transactions are irreversible.</li>
                        <li>Funds sent to the Pot or paid for services are non-refundable.</li>
                        <li>We do not guarantee any winnings or returns.</li>
                        <li>Game rules and point calculations may change at any time.</li>
                    </ul>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold text-charcoal-200">5. Limitation of Liability</h2>
                    <p className="text-charcoal-300 leading-relaxed">
                        To the maximum extent permitted by law, the creators of Wallet Roast shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to loss of funds, data, or reputation.
                    </p>
                </section>

                <div className="pt-8 border-t border-charcoal-800">
                    <a href="/" className="text-flame-400 hover:text-flame-300 font-medium transition-colors">
                        ← Back to Roast
                    </a>
                </div>
            </div>
        </main>
    );
}
